project_id = "foxdnspwzhjxjxuicute"

[functions.analyze-bites]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.post-to-outstand]
verify_jwt = false

[functions.resort-places-autocomplete]
verify_jwt = false
