import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { IMAGE_GENERATION_MODEL } from "../_shared/aiModelConstants.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// OG image dimensions
const OG_WIDTH = 1200;
const OG_HEIGHT = 630;

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { coverImageUrl, bookId, dailyPublishedId, seoMetadataId } = await req.json();

    if (!coverImageUrl) {
      throw new Error('coverImageUrl is required');
    }

    console.log(`Generating OG image for: ${coverImageUrl}`);

    // Fetch the original cover image
    const imageResponse = await fetch(coverImageUrl);
    if (!imageResponse.ok) {
      throw new Error(`Failed to fetch cover image: ${imageResponse.status}`);
    }

    const imageBlob = await imageResponse.blob();
    const imageArrayBuffer = await imageBlob.arrayBuffer();
    const mimeType = imageBlob.type || 'image/png';
    
    // Convert to base64 using chunked approach to avoid stack overflow
    const uint8Array = new Uint8Array(imageArrayBuffer);
    let base64Image = '';
    const chunkSize = 8192;
    for (let i = 0; i < uint8Array.length; i += chunkSize) {
      const chunk = uint8Array.slice(i, i + chunkSize);
      base64Image += String.fromCharCode(...chunk);
    }
    base64Image = btoa(base64Image);

    // Use Lovable AI to generate the letterboxed OG image
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    console.log('Calling AI to generate letterboxed OG image...');

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: IMAGE_GENERATION_MODEL,
        messages: [
          {
            role: "user",
            content: [
              {
                type: "text",
                text: `Create a 1200x630 pixel Open Graph image. Take this square book cover image and place it centered in the frame. Fill the left and right sides with an EXTREMELY blurred, heavily zoomed-in version of the same image as a very soft, dreamy background. Apply maximum gaussian blur so the background colors blend together smoothly with no recognizable details. The original cover should be clearly visible and sharp in the center, taking up most of the height. The ultra-blurred sides should blend seamlessly. Do not add any text or overlays - just the cover centered with heavily blurred background on the sides.`
              },
              {
                type: "image_url",
                image_url: {
                  url: `data:${mimeType};base64,${base64Image}`
                }
              }
            ]
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI API error:', errorText);
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log('AI response received');

    const generatedImageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    if (!generatedImageUrl) {
      throw new Error('No image generated by AI');
    }

    // Extract base64 data from data URL
    const base64Match = generatedImageUrl.match(/^data:([^;]+);base64,(.+)$/);
    if (!base64Match) {
      throw new Error('Invalid generated image format');
    }

    const generatedMimeType = base64Match[1];
    const generatedBase64 = base64Match[2];
    const generatedBuffer = Uint8Array.from(atob(generatedBase64), c => c.charCodeAt(0));

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Upload to storage
    const fileName = `og-images/${bookId || 'unknown'}-${Date.now()}.${generatedMimeType.includes('png') ? 'png' : 'jpg'}`;
    
    console.log(`Uploading OG image to: ${fileName}`);

    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('page-images')
      .upload(fileName, generatedBuffer, {
        contentType: generatedMimeType,
        upsert: true
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      throw new Error(`Failed to upload OG image: ${uploadError.message}`);
    }

    // Get public URL
    const { data: publicUrlData } = supabase.storage
      .from('page-images')
      .getPublicUrl(fileName);

    const ogImageUrl = publicUrlData.publicUrl;
    console.log(`OG image uploaded: ${ogImageUrl}`);

    // Update seo_metadata if ID provided
    if (seoMetadataId) {
      const { error: updateError } = await supabase
        .from('seo_metadata')
        .update({ og_image_url: ogImageUrl })
        .eq('id', seoMetadataId);

      if (updateError) {
        console.error('Failed to update seo_metadata:', updateError);
      } else {
        console.log('seo_metadata updated with new OG image URL');
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        ogImageUrl,
        message: 'OG image generated successfully'
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('Error generating OG image:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
