-- Seed existing resort data into locations table
INSERT INTO public.locations (id, label, emoji, description, spelling_guide, terrain, architecture, landmarks, color_palette, atmosphere, sort_order) VALUES
('VAIL_RESORT', 'Vail Resort', '🏔️', 'Colorado, world-class terrain', NULL, 
 'Massive back bowls, wide-open alpine terrain above treeline, dramatic Rocky Mountain peaks with consistent snowpack',
 'Bavarian-inspired alpine village with timber and stucco, clock towers, cobblestone walkways, upscale European aesthetic',
 ARRAY['Vail Village clock tower', 'Eagle Bahn Gondola', 'Blue Sky Basin', 'Two Elk Lodge', 'Golden Peak'],
 'Bright whites, deep blues, warm timber browns, gold accents',
 'Luxurious, world-class, European elegance meets Colorado grandeur', 1),

('SUGARBUSH_RESORT', 'Sugarbush Resort', '🍁', 'Vermont, classic New England', NULL,
 'Classic Vermont Green Mountain terrain, forested glades, varied natural terrain with Lincoln Peak and Mount Ellen',
 'Traditional New England ski lodge style, weathered wood, cozy base lodges, authentic Vermont character',
 ARRAY['Lincoln Peak', 'Mount Ellen', 'Slide Brook Express', 'Castlerock area', 'Valley House'],
 'Forest greens, maple reds, warm woods, sugar maple oranges',
 'Classic New England, family-oriented, authentic Vermont skiing heritage', 2),

('STRATTON', 'Stratton', '⛷️', 'Vermont, family-friendly', NULL,
 'Southern Vermont mountain with groomed intermediate terrain, forested slopes, family-friendly layout',
 'Modern alpine village base, clock tower, upscale Vermont aesthetic, well-maintained facilities',
 ARRAY['Stratton Village', 'Gondola base', 'Sun Bowl', 'World Cup trail', 'Clock tower'],
 'Clean whites, Vermont greens, classic red accents, timber browns',
 'Polished, family-friendly, Southern Vermont refinement', 3),

('KILLINGTON', 'Killington Mountain', '🏂', 'Vermont, the Beast of the East', 'K-I-L-L-I-N-G-T-O-N (note the G before T-O-N)',
 'Rugged Green Mountain terrain with exposed granite outcrops, dense hardwood/evergreen forests, moderate elevation peaks with natural bowl shapes',
 'Rustic Vermont-style lodges with brown/green wood siding, stone foundations, practical New England design',
 ARRAY['K-1 Gondola (red cabins)', 'Peak Lodge at summit', 'Snowshed base area', 'Superstar trail', 'Bear Mountain'],
 'Earthy greens, granite grays, autumn oranges/reds, deep forest greens',
 'Rugged, athletic, East Coast grit, unpretentious skiing culture', 4),

('MOUNTAIN_CREEK', 'Mountain Creek', '🎿', 'New Jersey, accessible fun', NULL,
 'Smaller New Jersey hills, accessible terrain parks, man-made snow focus, close-to-NYC convenience',
 'Modern resort facilities, practical lodge design, terrain park-focused infrastructure',
 ARRAY['Vernon Peak', 'South Peak', 'Granite Peak', 'Waterpark (summer)', 'Terrain parks'],
 'Bright action sports colors, grays, modern blues and greens',
 'Accessible, action-sports focused, suburban mountain escape, youthful energy', 5),

('COPPER_MOUNTAIN', 'Copper Mountain', '🥉', 'Colorado, naturally divided terrain', NULL,
 'Naturally divided terrain (beginner/intermediate/expert separated), Rocky Mountain alpine, above-treeline bowls',
 'Modern Colorado resort village, stone and timber, practical mountain design',
 ARRAY['Center Village', 'East Village', 'Copper Peak', 'Tucker Mountain', 'Woodward Barn'],
 'Copper/bronze tones, Colorado blue skies, pine greens, snow whites',
 'Laid-back Colorado vibe, terrain park culture, naturally organized mountain', 6),

('BRECKENRIDGE', 'Breckenridge', '🏘️', 'Colorado, historic mountain town', 'B-R-E-C-K-E-N-R-I-D-G-E',
 'High-altitude Rocky Mountain terrain, above-treeline alpine bowls, historic mining-town backdrop, five peaks',
 'Historic Victorian mining town Main Street, colorful painted buildings, preserved 1800s character with modern resort amenities',
 ARRAY['Peak 8', 'Peak 9', 'Main Street historic district', 'Imperial Express (highest chairlift)', 'BreckConnect Gondola'],
 'Victorian painted colors (blues, reds, yellows), historic wood tones, bright Colorado sunshine',
 'Historic charm, high-altitude adventure, vibrant town culture, Colorado heritage', 7),

('KEYSTONE', 'Keystone', '🌙', 'Colorado, night skiing', 'K-E-Y-S-T-O-N-E',
 'Three mountains (Dercum, North Peak, The Outback), night skiing terrain, varied difficulty, family-oriented layout',
 'Mountain village resort style, modern Colorado lodges, lakeside setting',
 ARRAY['River Run Village', 'Mountain House base', 'A51 Terrain Park', 'Keystone Lake', 'Outback bowls'],
 'Evening purples/blues (night skiing), warm lodge lighting, Colorado pine greens, starlit skies',
 'Family-friendly, famous night skiing, relaxed Colorado mountain village', 8),

('WHISTLER_BLACKCOMB', 'Whistler Blackcomb', '🇨🇦', 'British Columbia, largest ski resort in North America', 'W-H-I-S-T-L-E-R B-L-A-C-K-C-O-M-B (two words)',
 'Massive dual-mountain resort with dramatic coastal mountain peaks, alpine glaciers, steep chutes, legendary bowls, and extensive above-treeline terrain spanning 8,171 acres',
 'European-inspired pedestrian village with stone and timber construction, Pacific Northwest influences, modern luxury resort amenities, mountain chalets',
 ARRAY['Peak 2 Peak Gondola (record-breaking)', 'Whistler Village stroll', 'Blackcomb Glacier', 'Harmony Bowl', 'Horstman Glacier', '7th Heaven Express', 'Roundhouse Lodge'],
 'Pacific coastal blues, glacial whites, deep evergreen forests, dramatic cloud-shrouded peaks, Canadian red maple accents',
 'World-class luxury, Olympic heritage (2010 Winter Games), vibrant après-ski culture, cosmopolitan international vibe, raw coastal mountain grandeur', 9),

('PLATTEKILL', 'Plattekill Mountain', '🗽', 'New York, Catskills family-owned gem', 'P-L-A-T-T-E-K-I-L-L (double T, single L at end)',
 'Western Catskill Mountains terrain with 41 trails across 1,100 vertical feet, dense hardwood and hemlock forests, natural glades, classic Northeast mountain character with moderate steeps and rolling terrain',
 'Authentic family-owned lodge with rustic upstate New York character, weathered wood-sided base lodge, no-frills practical design, vintage ski area aesthetic preserved from old-school era',
 ARRAY['Double-black diamond Blockbuster trail', 'North Face steeps', 'Triple chairlift', 'Historic base lodge', 'Terrain park', 'Tubing hill'],
 'Catskill autumn colors (burnt orange, deep red, golden yellow), hardwood forest browns, hemlock greens, upstate New York gray skies, vintage lodge warm tones',
 'Throwback family-owned charm, last family-owned resort in northern Catskills, old-school Northeast skiing culture, unpretentious local vibe, 3 hours from NYC, no crowds, authentic upstate New York mountain experience', 10);