-- Add season, location, and city questions to all book agent types
-- These are optional contextual questions that allow users to customize their book's setting

INSERT INTO public.type_specific_discoveries (agent_type, question_key, question_text, options, sort_order, step_number, frontend_state_key, context_value_key, is_skippable, is_active)
VALUES
-- book-creation (generic fallback)
('book-creation', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-numbers
('book-creation-numbers', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-numbers', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-numbers', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-rhyming
('book-creation-rhyming', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-rhyming', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-rhyming', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-colors
('book-creation-colors', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-colors', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-colors', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-abc
('book-creation-abc', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-abc', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-abc', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-shapes
('book-creation-shapes', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-shapes', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-shapes', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-animals
('book-creation-animals', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-animals', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-animals', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-sight-words
('book-creation-sight-words', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-sight-words', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-sight-words', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-emotions
('book-creation-emotions', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-emotions', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-emotions', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-cvc
('book-creation-cvc', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-cvc', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-cvc', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-opposites (only needs location - already has season and city)
('book-creation-opposites', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),

-- book-creation-first-words
('book-creation-first-words', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-first-words', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-first-words', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-bedtime
('book-creation-bedtime', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-bedtime', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-bedtime', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-general
('book-creation-general', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-general', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-general', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-digraphs
('book-creation-digraphs', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-digraphs', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-digraphs', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-dr-seuss
('book-creation-dr-seuss', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-dr-seuss', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-dr-seuss', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true),

-- book-creation-parent-education
('book-creation-parent-education', 'season', 'Would you like the book to have a seasonal theme? This is optional.', '[{"key": "spring", "label": "🌸 Spring"}, {"key": "summer", "label": "☀️ Summer"}, {"key": "fall", "label": "🍂 Fall"}, {"key": "winter", "label": "❄️ Winter"}, {"key": "skip", "label": "No preference"}]'::jsonb, 100, 10, 'selectedSeason', 'season', true, true),
('book-creation-parent-education', 'location', 'Would you like to set this book at a specific ski resort? This is optional.', '[{"key": "vail", "label": "⛷️ Vail"}, {"key": "sugarbush", "label": "⛷️ Sugarbush"}, {"key": "stratton", "label": "⛷️ Stratton"}, {"key": "killington", "label": "⛷️ Killington"}, {"key": "mountain-creek", "label": "⛷️ Mountain Creek"}, {"key": "copper-mountain", "label": "⛷️ Copper Mountain"}, {"key": "breckenridge", "label": "⛷️ Breckenridge"}, {"key": "keystone", "label": "⛷️ Keystone"}, {"key": "whistler-blackcomb", "label": "⛷️ Whistler Blackcomb"}, {"key": "plattekill", "label": "⛷️ Plattekill"}, {"key": "skip", "label": "No preference"}]'::jsonb, 101, 11, 'selectedLocation', 'location', true, true),
('book-creation-parent-education', 'city', 'Would you like to set this book in a specific city? This is optional.', '[{"key": "jersey-city", "label": "🏙️ Jersey City"}, {"key": "hoboken", "label": "🏙️ Hoboken"}, {"key": "new-york-city", "label": "🗽 New York City"}, {"key": "skip", "label": "No preference"}]'::jsonb, 102, 12, 'selectedCity', 'city', true, true);