/**
 * @fileoverview Supabase client configuration
 * 
 * This file configures and exports the Supabase client instance used throughout
 * the ABC Cards application. It handles authentication, database operations,
 * storage, and real-time subscriptions.
 * 
 * Configuration:
 * - Persistent authentication sessions using localStorage
 * - Automatic token refresh for seamless user experience
 * - TypeScript integration with generated database types
 * 
 * @version 1.0.0
 * @author ABC Cards Team
 * @note This file is automatically generated. Do not edit it directly.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Supabase project URL */
const SUPABASE_URL = "https://foxdnspwzhjxjxuicute.supabase.co";

/** Supabase anon/public key for client-side operations */
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZveGRuc3B3emhqeGp4dWljdXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjcyNzQsImV4cCI6MjA3Mjc0MzI3NH0.3VchRK3xfYxZCWBjZpWUwkKTsIB4qAqvNbje_ByXnLI";

/**
 * Configured Supabase client instance
 * 
 * Pre-configured client with authentication persistence and automatic token refresh.
 * Use this instance throughout the application for all Supabase operations.
 * 
 * Features:
 * - localStorage-based session persistence
 * - Automatic token refresh
 * - TypeScript database type integration
 * 
 * @example
 * ```typescript
 * import { supabase } from "@/integrations/supabase/client";
 * 
 * // Query data
 * const { data, error } = await supabase
 *   .from('books')
 *   .select('*')
 *   .eq('user_id', userId);
 * 
 * // Call edge function
 * const { data, error } = await supabase.functions.invoke('chat', {
 *   body: { message: 'Hello' }
 * });
 * ```
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});